/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

import datastructures.linkedlist.LinkedList;
import org.testng.annotations.Test;
//import static org.junit.jupiter.api.Assertions.*;
import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        linkedlist.Library classUnderTest = new linkedlist.Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
